"""Deterministic stub engine for offline v2 end-to-end testing."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from harness.engines.base import Engine, EngineResponse


class MockResponseSet:
    """Container for canned mock responses used by :class:`MockEngine`."""

    def __init__(self, fixtures: dict[str, str] | None = None) -> None:
        self.fixtures: dict[str, str] = fixtures or {}


class MockEngine(Engine):
    """Deterministic stub engine for offline testing.

    Reads canned responses from ``HARNESS_MOCK_FIXTURE_PATH`` (a JSON file
    mapping prompt-substring → response text) or falls back to built-in
    planner / worker stubs.
    """

    default_model = "mock-v1"

    def __init__(self) -> None:
        # No API key required.
        pass

    @property
    def name(self) -> str:
        return "mock"

    def dispatch(
        self,
        packet_content: str,
        model: str,
        extra_args: dict[str, Any] | None = None,
    ) -> EngineResponse:
        # 1. Fixture file override
        fixture_path = os.environ.get("HARNESS_MOCK_FIXTURE_PATH")
        if fixture_path:
            try:
                fixtures = json.loads(Path(fixture_path).read_text(encoding="utf-8"))
                for key, response in fixtures.items():
                    if key in packet_content:
                        return EngineResponse(
                            success=True,
                            text=response,
                            latency_ms=10,
                            error=None,
                        )
            except Exception:
                pass  # fall through to builtins

        # 2. Planner-style stub
        if "WavePlan" in packet_content or "decompose" in packet_content.lower():
            return EngineResponse(
                success=True,
                text=_default_waveplan_stub(packet_content),
                latency_ms=10,
                error=None,
            )

        # 3. Worker-style stub
        return EngineResponse(
            success=True,
            text=_default_worker_stub(packet_content),
            latency_ms=10,
            error=None,
        )


def _default_waveplan_stub(packet: str) -> str:
    """Return a stub WavePlan JSON for the planner."""
    plan = {
        "schema_version": 1,
        "run_id": "MOCK-RUN-ID-PLACEHOLDER",
        "spec_path": "mock",
        "created_at": "2026-05-21T00:00:00+00:00",
        "planner_engine": "mock",
        "tasks": [
            {
                "worker_id": "worker-1",
                "title": "Mock task 1",
                "description": "Stub task for MockEngine smoke test",
                "read_set": ["README.md"],
                "write_set": ["mock-out-1.txt"],
                "test_set": [],
                "depends_on": [],
                "steps": [
                    {
                        "step_id": "s1",
                        "kind": "create",
                        "instruction": "Write hello to mock-out-1.txt",
                        "target_files": ["mock-out-1.txt"],
                        "expected_diff_lines": 1,
                        "required_tests": [],
                    }
                ],
                "estimated_kimi_minutes": 1,
                "max_context_tokens": 1000,
            }
        ],
        "integration_strategy": "squash",
        "notes": "Generated by MockEngine for offline test",
    }
    return f"```json\n{json.dumps(plan, indent=2)}\n```"


def _default_worker_stub(packet: str) -> str:
    """Return a stub FILE/REPLACE block for worker steps."""
    return """<FILE: mock-out-1.txt>
hello from MockEngine
</FILE>
"""
