"""W14-CLAUDE-CODE-WRAPPER-SCRIPTS 2026-05-26: generate per-provider
wrapper scripts that pre-configure ``claude`` for a specific provider.

Each wrapper is a thin shell/cmd script that:
  - Sets ``ANTHROPIC_BASE_URL``, ``ANTHROPIC_AUTH_TOKEN``, model aliases
  - exec's the real ``claude`` binary with ``--bare``

Wrappers contain ONLY URLs (public knowledge) and references to env-var
names (operator's actual keys stay in their shell env).  No secrets in
wrapper files.

Result: operator types ``claude-mimo "prompt"`` in any terminal and
gets MiMo via Claude Code with the legitimate ``claude/<version>`` UA
— without ever needing to set ANTHROPIC_BASE_URL manually.

Usage:
  ``harness engines install-wrappers``    install for available providers
  ``harness engines list-wrappers``       show what's installed

The harness CLI commands are wired in ``cli.py``; this module exposes
the data layer (templates, install logic, listing).
"""
from __future__ import annotations

import os
import platform
import stat
from pathlib import Path
from typing import Optional

from harness.engines.claude_code_subprocess import (
    DEFAULT_MODEL_PER_ENGINE,
    PROVIDER_ANTHROPIC_ENDPOINTS,
)


# Default install location.  Operator must add this to PATH for the
# wrappers to be invocable as bare names.
DEFAULT_WRAPPER_DIR: Path = Path.home() / ".harness" / "bin"


# Per-provider wrapper definitions: each entry pairs an engine key
# from PROVIDER_ANTHROPIC_ENDPOINTS with the env-var name holding the
# operator's API key.  Wrappers reference $VAR_NAME so secrets stay
# in the operator's shell environment.
WRAPPER_DEFINITIONS: dict[str, dict[str, str]] = {
    # MiMo Token Plan SGP — operator's default since MIMO_API_KEY is tp-
    "claude-mimo": {
        "engine_key": "mimo-tp-sgp",
        "key_env": "MIMO_API_KEY",
        "description": "MiMo Token Plan (SGP) via Claude Code",
    },
    # MiMo Pay-as-you-go (for operators with sk- prefixed keys)
    "claude-mimo-payg": {
        "engine_key": "mimo-payg",
        "key_env": "MIMO_API_KEY",
        "description": "MiMo Pay-as-you-go via Claude Code",
    },
    # Kimi — Kimi Code subscription endpoint.  W14-KIMI-VIA-CLAUDE
    # 2026-05-26: account restored after the 2026-05-25 termination
    # was rolled back into a friendlier UA-gate redirect.  Operator's
    # existing KIMI_API_KEY works against api.kimi.com/coding when
    # Claude Code's legitimate UA passes the allowlist gate.
    "claude-kimi": {
        "engine_key": "kimi-via-cc",
        "key_env": "KIMI_API_KEY",
        "description": "Kimi Code (Moonshot K2.6) via Claude Code",
    },
    # DeepSeek via Claude Code — multimodal silent-drop applies; the
    # operator should see the docstring caveat when using the wrapper.
    "claude-deepseek": {
        "engine_key": "deepseek-via-cc",
        "key_env": "DEEPSEEK_API_KEY",
        "description": ("DeepSeek via Claude Code "
                         "(text + tool use only — drops multimodal)"),
    },
    # GLM via Claude Code — when operator subscribes to z.ai Coding Plan
    # or uses GLM_API_KEY PAYG.
    "claude-glm": {
        "engine_key": "glm-via-cc",
        "key_env": "GLM_API_KEY",
        "description": "GLM (Zhipu) via Claude Code",
    },
    # Qwen via Claude Code (DashScope) — Qwen's docs prefer
    # ANTHROPIC_API_KEY (not _AUTH_TOKEN); wrappers set both for safety.
    "claude-qwen": {
        "engine_key": "qwen-via-cc",
        "key_env": "DASHSCOPE_API_KEY",
        "description": "Qwen (Alibaba DashScope) via Claude Code",
    },
}


# Provider endpoints + default models for the wrappers that aren't yet
# in PROVIDER_ANTHROPIC_ENDPOINTS (kimi-via-cc and mimo-* are there
# already from W14-PATTERN-B-CLAUDE-CODE-SUBPROCESS).  Centralizing
# here keeps wrapper-script generation self-contained.
WRAPPER_PROVIDER_ENDPOINTS: dict[str, str] = {
    **PROVIDER_ANTHROPIC_ENDPOINTS,
    # Future engines not yet wired in concrete.py but ready in wrappers
    "deepseek-via-cc": "https://api.deepseek.com/anthropic",
    "glm-via-cc": "https://api.z.ai/api/anthropic",
    "qwen-via-cc": "https://dashscope-intl.aliyuncs.com/apps/anthropic",
}


WRAPPER_DEFAULT_MODELS: dict[str, str] = {
    **DEFAULT_MODEL_PER_ENGINE,
    "deepseek-via-cc": "deepseek-v4-pro",
    "glm-via-cc": "glm-5.1",
    "qwen-via-cc": "qwen3.6-plus",
}


POSIX_WRAPPER_TEMPLATE = """\
#!/bin/bash
# {wrapper_name} -- generated by 'harness engines install-wrappers'
# Description: {description}
# Endpoint: {endpoint}
# Default model: {default_model}
#
# This wrapper invokes the real ``claude`` binary with ANTHROPIC_BASE_URL
# redirected at the provider's Anthropic-compatible endpoint.  The wire-
# level HTTP call carries Claude Code's legitimate ``claude/<version>``
# User-Agent, satisfying the provider's allowlist.  TOS-compliant: no
# spoofing, the binary IS Claude Code.
#
# Set ${key_env} in your shell before invoking.  The wrapper does NOT
# embed any secret.

if [ -z "${{{key_env}}}" ]; then
  echo "Error: {key_env} is not set." >&2
  echo "Set it in your shell environment first:" >&2
  echo "  export {key_env}=your-api-key" >&2
  exit 64
fi

exec env \\
  ANTHROPIC_BASE_URL="{endpoint}" \\
  ANTHROPIC_AUTH_TOKEN="${{{key_env}}}" \\
  ANTHROPIC_API_KEY="${{{key_env}}}" \\
  ANTHROPIC_MODEL="{default_model}" \\
  ANTHROPIC_DEFAULT_SONNET_MODEL="{default_model}" \\
  ANTHROPIC_DEFAULT_OPUS_MODEL="{default_model}" \\
  ANTHROPIC_DEFAULT_HAIKU_MODEL="{default_model}" \\
  CLAUDE_CODE_SUBAGENT_MODEL="{default_model}" \\
  ENABLE_TOOL_SEARCH="false" \\
  claude --bare "$@"
"""


WINDOWS_WRAPPER_TEMPLATE = """\
@echo off
:: {wrapper_name}.cmd -- generated by 'harness engines install-wrappers'
:: Description: {description}
:: Endpoint: {endpoint}
:: Default model: {default_model}

if "%{key_env}%"=="" (
  echo Error: {key_env} is not set. 1>&2
  echo Set it in your shell environment first: 1>&2
  echo   set {key_env}=your-api-key 1>&2
  exit /b 64
)

set "ANTHROPIC_BASE_URL={endpoint}"
set "ANTHROPIC_AUTH_TOKEN=%{key_env}%"
set "ANTHROPIC_API_KEY=%{key_env}%"
set "ANTHROPIC_MODEL={default_model}"
set "ANTHROPIC_DEFAULT_SONNET_MODEL={default_model}"
set "ANTHROPIC_DEFAULT_OPUS_MODEL={default_model}"
set "ANTHROPIC_DEFAULT_HAIKU_MODEL={default_model}"
set "CLAUDE_CODE_SUBAGENT_MODEL={default_model}"
set "ENABLE_TOOL_SEARCH=false"

claude --bare %*
"""


def _is_windows() -> bool:
    """W14-CLAUDE-CODE-WRAPPER-SCRIPTS: detect if we're on Windows.

    POSIX path is used on Linux/Mac/Git-Bash.  Windows .cmd is generated
    only when ``platform.system() == "Windows"`` AND the operator hasn't
    forced POSIX via ``HARNESS_WRAPPER_FORMAT=posix``.
    """
    forced = os.environ.get("HARNESS_WRAPPER_FORMAT", "").lower()
    if forced == "windows":
        return True
    if forced == "posix":
        return False
    return platform.system() == "Windows"


def _render_wrapper(
    wrapper_name: str,
    spec: dict[str, str],
    *,
    use_windows: Optional[bool] = None,
) -> tuple[str, str]:
    """Render a wrapper script.  Returns (filename, contents).

    ``use_windows=None`` auto-detects; explicit True/False is for tests.
    """
    win = use_windows if use_windows is not None else _is_windows()
    template = WINDOWS_WRAPPER_TEMPLATE if win else POSIX_WRAPPER_TEMPLATE
    suffix = ".cmd" if win else ""
    filename = f"{wrapper_name}{suffix}"

    engine_key = spec["engine_key"]
    endpoint = WRAPPER_PROVIDER_ENDPOINTS.get(engine_key, "")
    default_model = WRAPPER_DEFAULT_MODELS.get(engine_key, "")

    contents = template.format(
        wrapper_name=wrapper_name,
        description=spec["description"],
        endpoint=endpoint,
        default_model=default_model,
        key_env=spec["key_env"],
    )
    return filename, contents


def install_wrappers(
    *,
    target_dir: Optional[Path] = None,
    only: Optional[list[str]] = None,
    use_windows: Optional[bool] = None,
    overwrite: bool = True,
) -> dict[str, dict]:
    """Generate + install all (or selected) wrapper scripts to disk.

    Args:
      target_dir: directory to install into.  Defaults to ~/.harness/bin.
      only: list of wrapper names (e.g. ["claude-mimo", "claude-qwen"])
        to install; ``None`` installs all defined wrappers.
      use_windows: force Windows / POSIX wrapper format.  ``None``
        auto-detects.
      overwrite: if False, skip wrappers that already exist.

    Returns a dict mapping each wrapper name to ``{"path": str,
    "status": "installed" | "skipped" | "skipped-exists", "endpoint":
    str, "default_model": str}``.
    """
    dest = target_dir or DEFAULT_WRAPPER_DIR
    dest.mkdir(parents=True, exist_ok=True)

    selected = only if only is not None else list(WRAPPER_DEFINITIONS.keys())
    result: dict[str, dict] = {}
    for wrapper_name in selected:
        spec = WRAPPER_DEFINITIONS.get(wrapper_name)
        if spec is None:
            result[wrapper_name] = {
                "status": "skipped",
                "reason": f"unknown wrapper: {wrapper_name}",
                "path": None,
            }
            continue
        filename, contents = _render_wrapper(
            wrapper_name, spec, use_windows=use_windows,
        )
        path = dest / filename
        if path.exists() and not overwrite:
            result[wrapper_name] = {
                "status": "skipped-exists",
                "path": str(path),
                "endpoint": WRAPPER_PROVIDER_ENDPOINTS.get(
                    spec["engine_key"], "",
                ),
                "default_model": WRAPPER_DEFAULT_MODELS.get(
                    spec["engine_key"], "",
                ),
            }
            continue
        path.write_text(contents, encoding="utf-8")
        # On POSIX, mark executable
        if not (use_windows if use_windows is not None else _is_windows()):
            try:
                path.chmod(path.stat().st_mode | stat.S_IXUSR
                           | stat.S_IXGRP | stat.S_IXOTH)
            except (OSError, NotImplementedError):
                # Best effort; chmod can fail on some Windows-emulation
                # filesystems even when we're in posix mode for tests.
                pass
        result[wrapper_name] = {
            "status": "installed",
            "path": str(path),
            "endpoint": WRAPPER_PROVIDER_ENDPOINTS.get(
                spec["engine_key"], "",
            ),
            "default_model": WRAPPER_DEFAULT_MODELS.get(
                spec["engine_key"], "",
            ),
        }
    return result


def list_wrappers(
    target_dir: Optional[Path] = None,
) -> list[dict]:
    """Return per-wrapper installation status.

    Each entry has: name, expected_path, installed (bool),
    description, endpoint, default_model, key_env.
    """
    dest = target_dir or DEFAULT_WRAPPER_DIR
    suffix = ".cmd" if _is_windows() else ""
    out = []
    for wrapper_name, spec in WRAPPER_DEFINITIONS.items():
        engine_key = spec["engine_key"]
        path = dest / f"{wrapper_name}{suffix}"
        out.append({
            "name": wrapper_name,
            "expected_path": str(path),
            "installed": path.exists(),
            "description": spec["description"],
            "endpoint": WRAPPER_PROVIDER_ENDPOINTS.get(engine_key, ""),
            "default_model": WRAPPER_DEFAULT_MODELS.get(engine_key, ""),
            "key_env": spec["key_env"],
            "key_present": bool(os.environ.get(spec["key_env"])),
        })
    return out


def get_path_hint() -> Optional[str]:
    """Return a hint about adding the wrapper dir to PATH if missing.
    ``None`` when the dir is already on PATH.  Used by CLI to guide
    the operator after install.
    """
    dest = str(DEFAULT_WRAPPER_DIR.resolve())
    current_path = os.environ.get("PATH", "")
    path_components = current_path.split(os.pathsep)
    if dest in path_components:
        return None
    if _is_windows():
        return (
            f"Add the wrapper dir to PATH:\n"
            f"  PowerShell:  [Environment]::SetEnvironmentVariable("
            f"\"PATH\", \"$env:PATH;{dest}\", [EnvironmentVariableTarget]::User)\n"
            f"  cmd:         setx PATH \"%PATH%;{dest}\""
        )
    return (
        f"Add the wrapper dir to PATH (add to ~/.bashrc or ~/.zshrc):\n"
        f"  export PATH=\"$PATH:{dest}\""
    )
