"""W11-AGENT-INIT-VERB: bootstrap a fresh project for agentic use of the harness.

Public API:
    init_project(target, project_type="python", adapter_name=None,
                 dry_run=False, allow_self=False) -> InitResult

Writes a small file tree to *target* that lets an agentic coding agent
(Claude Code, Cursor, Aider, ChatGPT with code interpreter) immediately
dispatch work via the harness without spending engineering hours on
scaffolding.

File tree written:

    target/
    ├── .env                 # API-key template; never silently overwritten
    ├── .gitignore           # only if absent; ignores .env + .harness/
    ├── adapter.py           # single-file starter adapter; skipped if exists
    ├── CLAUDE.md            # appended (with marker) if exists; created otherwise
    └── .harness/
        ├── config.json      # project metadata (created_at, etc.)
        ├── STATUS.csv       # header row only; project-scoped
        └── dispatched/      # cache dir (gitkeep'd)
            └── .gitkeep

Safety contract:
    - Refuses to run on the harness's own repo (self-target) unless
      --allow-self is passed.
    - Never silently overwrites existing files; .env and adapter.py
      are skip-on-exist; CLAUDE.md is append-on-exist (via marker);
      .harness/STATUS.csv with rows raises StatusCollisionError.
"""

from __future__ import annotations

import json
import os
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal


ProjectType = Literal["python", "node", "generic"]
ALLOWED_PROJECT_TYPES: tuple[ProjectType, ...] = ("python", "node", "generic")


class InitError(Exception):
    """Base exception for agent-init failures."""


class SelfTargetRefused(InitError):
    """Raised when --target resolves to the harness repo and --allow-self
    is not passed.  W11-AGENT-INIT-VERB safety contract."""


class StatusCollisionError(InitError):
    """Raised when target has an existing .harness/STATUS.csv with
    data rows.  Operator must merge manually."""


@dataclass
class InitResult:
    """Result of init_project — what was written + skipped + the
    next-command teach block to print to the operator."""
    target: Path
    project_type: ProjectType
    adapter_name: str
    created: list[Path] = field(default_factory=list)
    skipped: list[tuple[Path, str]] = field(default_factory=list)  # (path, reason)
    appended: list[Path] = field(default_factory=list)
    dry_run: bool = False


# -- helpers ---------------------------------------------------------------


def _is_harness_repo(path: Path) -> bool:
    """Detect if *path* is the harness's own repo (self-target check).

    Heuristic: contains both `src/harness/__init__.py` AND `coord/STATUS.csv`
    AND `spec/multi-agent-harness-architecture.md` (load-bearing harness files).
    """
    path = path.resolve()
    markers = [
        path / "src" / "harness" / "__init__.py",
        path / "coord" / "STATUS.csv",
        path / "spec" / "multi-agent-harness-architecture.md",
    ]
    return all(m.exists() for m in markers)


def _pascal_case(s: str) -> str:
    """Convert 'my-project' / 'my_project' / 'My Project' -> 'MyProject'."""
    parts = []
    for chunk in s.replace("_", "-").replace(" ", "-").split("-"):
        if chunk:
            parts.append(chunk[0].upper() + chunk[1:])
    return "".join(parts) or "AgentProject"


# -- file templates --------------------------------------------------------


_ENV_TEMPLATE = """\
# Harness agent secrets — never commit this file.
# Populated by `harness env-wizard` or by hand.
HARNESS_KIMI_API_KEY=
HARNESS_DEEPSEEK_API_KEY=
HARNESS_MIMO_API_KEY=
HARNESS_ANTHROPIC_API_KEY=
HARNESS_GEMINI_API_KEY=
# HARNESS_ENCRYPT_WITH_DPAPI=1  # Windows-only: store secrets in DPAPI
# HARNESS_COST_MAX_PER_SESSION=5.00  # cost ceiling per session (USD)
"""


_GITIGNORE_TEMPLATE = """\
# Harness agent state
.env
.harness/
__pycache__/
*.pyc
"""


def _adapter_template(project_name: str, adapter_class: str,
                      project_type: ProjectType) -> str:
    """Return the starter adapter.py template."""
    if project_type == "node":
        purpose = "Node/JS project — Kimi for code, DeepSeek for review."
    elif project_type == "generic":
        purpose = "Generic project — default routing."
    else:
        purpose = "Python project — Kimi for code, DeepSeek for review."
    return (
        f'"""Starter adapter for {project_name} ({project_type}).\n\n'
        f'{purpose}\n\n'
        f"Generated by `harness agent init` (W11-AGENT-INIT-VERB).\n"
        f'Edit DEFAULT_ENGINES + routing as needed.  Re-run\n'
        f'`harness agent init --target . --overwrite` to refresh '
        f"(does NOT overwrite this file — delete first).\n"
        f'\n'
        f"Upgrade path: when this file outgrows single-file complexity,\n"
        f"convert to a package: mkdir adapter/ && mv adapter.py "
        f"adapter/__init__.py + add prompts.py / parsers.py as needed.\n"
        f'"""\n'
        f"\n"
        f"PROJECT_NAME = \"{project_name}\"\n"
        f"ADAPTER_NAME = \"{adapter_class}\"\n"
        f"\n"
        f"# Routing config — agent edits this to map work to engines.\n"
        f"DEFAULT_ENGINES = {{\n"
        f"    \"kimi\": {{\n"
        f"        \"model\": \"kimi-k2.6\",\n"
        f"        \"api_key_env\": \"HARNESS_KIMI_API_KEY\",\n"
        f"        \"role\": \"code\",\n"
        f"    }},\n"
        f"    \"deepseek\": {{\n"
        f"        \"model\": \"deepseek-v4-flash\",\n"
        f"        \"api_key_env\": \"HARNESS_DEEPSEEK_API_KEY\",\n"
        f"        \"role\": \"review\",\n"
        f"    }},\n"
        f"}}\n"
        f"\n"
        f"FALLBACK_CHAIN = [\"kimi\", \"deepseek\"]\n"
    )


def _claude_md_template(project_name: str) -> str:
    """Return the agent-context snippet to append to CLAUDE.md.

    Kept ≤800 chars per W11-CLAUDE-MD-TEMPLATE merge spec.
    """
    return (
        "\n\n---\n"
        "<!-- harness:agent-init -->\n"
        "## Harness Agent Context\n\n"
        f"This project uses **xaxiu-harness** for multi-engine dispatch.\n"
        f"\n"
        f"**Daily commands** (single-verb operations):\n"
        f"- `harness dispatch <packet.md>` — route work to the best engine\n"
        f"- `harness retrieve <id> --scope summary` — get a dispatch result\n"
        f"- `harness budget` — see session cost + offload ratio\n"
        f"\n"
        f"**Config**: `adapter.py` defines engine routing; `.env` holds keys.\n"
        f"\n"
        f"**Status**: `.harness/STATUS.csv` tracks this project's tasks "
        f"(distinct from the harness's own STATUS.csv).\n"
        f"\n"
        f"**See also**: `harness --help` for daily verbs, "
        f"`harness advanced list` for engineering verbs.\n"
    )


def _config_json(project_name: str, adapter_class: str,
                 project_type: ProjectType) -> dict:
    return {
        "schema_version": 1,
        "project_name": project_name,
        "adapter_module": "adapter",
        "adapter_class": adapter_class,
        "project_type": project_type,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "init_version": "w11-agent-init-verb",
    }


# Header for project-scoped STATUS.csv (distinct columns from harness's own).
_STATUS_CSV_HEADER = (
    "timestamp,dispatch_id,engine,model,tokens_in,tokens_out,"
    "duration_ms,cost_usd,status,error\n"
)


# -- main entry point ------------------------------------------------------


def init_project(target: Path | str,
                 project_type: ProjectType = "python",
                 adapter_name: str | None = None,
                 dry_run: bool = False,
                 allow_self: bool = False) -> InitResult:
    """Bootstrap *target* for agentic harness use.

    See module docstring for full contract.  Raises:
        ValueError: invalid project_type
        SelfTargetRefused: target is harness repo + allow_self=False
        StatusCollisionError: target has .harness/STATUS.csv with rows
        OSError: filesystem failure (passed through)
    """
    if project_type not in ALLOWED_PROJECT_TYPES:
        raise ValueError(
            f"unknown project_type {project_type!r}; allowed: "
            f"{ALLOWED_PROJECT_TYPES}"
        )

    target = Path(target).resolve()
    if not allow_self and _is_harness_repo(target):
        raise SelfTargetRefused(
            f"--target {target} resolves to the harness's own repo.  "
            f"Refusing to bootstrap on top of the harness itself.  "
            f"Pass --allow-self to override (use only when you "
            f"explicitly know what you're doing)."
        )

    # Derive adapter name from target basename if not given
    if adapter_name is None:
        adapter_name = _pascal_case(target.name) + "Adapter"
    project_name = target.name

    result = InitResult(target=target, project_type=project_type,
                        adapter_name=adapter_name, dry_run=dry_run)

    if dry_run:
        # Plan-only: record what WOULD happen without touching disk
        return _plan_dry_run(target, project_name, adapter_name,
                              project_type, result)

    # Create target if missing
    target.mkdir(parents=True, exist_ok=True)
    harness_dir = target / ".harness"
    harness_dir.mkdir(parents=True, exist_ok=True)

    # STATUS.csv collision check FIRST (data-loss risk)
    status_path = harness_dir / "STATUS.csv"
    if status_path.exists():
        # Read line count; > 1 means has data rows beyond header
        try:
            existing_lines = status_path.read_text(
                encoding="utf-8", errors="replace"
            ).splitlines()
            data_rows = [ln for ln in existing_lines[1:] if ln.strip()]
            if data_rows:
                raise StatusCollisionError(
                    f"{status_path} already contains {len(data_rows)} "
                    f"row(s) of dispatch history.  Refusing to overwrite "
                    f"(data file; operator must merge manually)."
                )
        except OSError:
            # Couldn't read — be cautious and skip
            result.skipped.append((status_path, "exists; couldn't verify content"))

    # .env (skip if exists; operator may have real secrets)
    env_path = target / ".env"
    if env_path.exists():
        result.skipped.append((env_path, "exists (preserve operator secrets)"))
    else:
        env_path.write_text(_ENV_TEMPLATE, encoding="utf-8")
        result.created.append(env_path)

    # .gitignore (only if absent)
    gi_path = target / ".gitignore"
    if gi_path.exists():
        result.skipped.append((gi_path, "exists"))
    else:
        gi_path.write_text(_GITIGNORE_TEMPLATE, encoding="utf-8")
        result.created.append(gi_path)

    # adapter.py (skip if exists; never overwrite operator's code)
    adapter_path = target / "adapter.py"
    if adapter_path.exists():
        result.skipped.append((adapter_path, "exists (preserve operator code)"))
    else:
        adapter_path.write_text(
            _adapter_template(project_name, adapter_name, project_type),
            encoding="utf-8",
        )
        result.created.append(adapter_path)

    # CLAUDE.md — append with marker, or create
    claude_path = target / "CLAUDE.md"
    snippet = _claude_md_template(project_name)
    if claude_path.exists():
        existing = claude_path.read_text(encoding="utf-8", errors="replace")
        if "<!-- harness:agent-init -->" in existing:
            result.skipped.append((claude_path, "already has harness:agent-init marker"))
        else:
            claude_path.write_text(existing + snippet, encoding="utf-8")
            result.appended.append(claude_path)
    else:
        claude_path.write_text(snippet.lstrip("\n"), encoding="utf-8")
        result.created.append(claude_path)

    # .harness/config.json
    config_path = harness_dir / "config.json"
    if config_path.exists():
        result.skipped.append((config_path, "exists (existing harness project)"))
    else:
        config_path.write_text(
            json.dumps(_config_json(project_name, adapter_name, project_type),
                       indent=2),
            encoding="utf-8",
        )
        result.created.append(config_path)

    # .harness/STATUS.csv (header-only; if missing — collision was handled above)
    if not status_path.exists():
        status_path.write_text(_STATUS_CSV_HEADER, encoding="utf-8")
        result.created.append(status_path)

    # .harness/dispatched/.gitkeep
    dispatched_dir = harness_dir / "dispatched"
    dispatched_dir.mkdir(parents=True, exist_ok=True)
    gitkeep = dispatched_dir / ".gitkeep"
    if not gitkeep.exists():
        gitkeep.write_text("", encoding="utf-8")
        result.created.append(gitkeep)

    return result


def _plan_dry_run(target: Path, project_name: str, adapter_name: str,
                  project_type: ProjectType,
                  result: InitResult) -> InitResult:
    """Return a result describing what init_project WOULD do without
    touching disk.  Same exit-code contract as the real path."""
    harness_dir = target / ".harness"
    plans = [
        (target / ".env", _ENV_TEMPLATE),
        (target / ".gitignore", _GITIGNORE_TEMPLATE),
        (target / "adapter.py",
         _adapter_template(project_name, adapter_name, project_type)),
        (target / "CLAUDE.md", _claude_md_template(project_name)),
        (harness_dir / "config.json",
         json.dumps(_config_json(project_name, adapter_name, project_type),
                    indent=2)),
        (harness_dir / "STATUS.csv", _STATUS_CSV_HEADER),
        (harness_dir / "dispatched" / ".gitkeep", ""),
    ]
    for p, _ in plans:
        if p.exists():
            result.skipped.append((p, "exists"))
        else:
            result.created.append(p)
    return result


def render_next_steps(result: InitResult) -> str:
    """Return the operator-facing "what to do next" teach block."""
    if result.dry_run:
        return f"DRY RUN — would create {len(result.created)} files in {result.target}/  (re-run without --dry-run to apply)"
    return (
        f"✓ Initialized agent project at {result.target}/\n"
        f"\n"
        f"  Created {len(result.created)} file(s); "
        f"skipped {len(result.skipped)}; appended {len(result.appended)}.\n"
        f"\n"
        f"  Next steps for the agent:\n"
        f"\n"
        f"    1. Fill in API keys in .env:\n"
        f"       harness env-wizard\n"
        f"\n"
        f"    2. Validate the starter adapter:\n"
        f"       harness adapter validate {result.target.name} --json\n"
        f"\n"
        f"    3. Dispatch your first packet:\n"
        f"       harness dispatch path/to/packet.md --backend kimi\n"
        f"\n"
        f"    4. Retrieve the result:\n"
        f"       harness retrieve <dispatch_id> --scope summary\n"
        f"\n"
        f"  Daily check-in:  harness daily\n"
        f"  Cost + offload:  harness budget\n"
    )
